# Generated by Django 5.0.4 on 2024-05-08 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauthapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
