# Generated by Django 5.0.4 on 2024-05-08 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauthapp', '0004_alter_customuser_managers_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
